Fix static file caching issue
adobe/aio-lib-web pull request #135
Opened 2020-12-16 05:16 UTC by sandeep-paliwal

Content hash was not included in file names when parcel bundle was generated. This created same file name for static content which was referenced in HTML file. With same file name cached version of file was used and latest changes were not reflected to user.

## Description
Fix is to use the content hash option provided by parcel bundler.

## Related Issue

## Motivation and Context

## How Has This Been Tested?
manual app deploy
run unit tests

## Screenshots (if appropriate):

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

2020-12-16 09:26 UTC, meryllblanchet commented
Fixes #136

2020-12-16 10:01 UTC, shazron commented
A few issues:
1. Please update the CI to use GIthub Actions. see aio-cli for the [file](https://github.com/adobe/aio-cli/blob/master/.github/workflows/node.js.yml). Make sure in the repo settings Github Actions is enabled as well.
2. Remove the .travis.yml file
3. Remove the Travis CI build badge in the README.md
4. Add the Github Actions build badge in the README.md (see aio-cli [README](https://raw.githubusercontent.com/adobe/aio-cli/master/README.md))
5. Add a test to see if the bundler options in the build-web call will always be called with `contentHash: true`
6. Branch protection for master branch in repo settings -> check the appropriate checkboxes for the new CI tests. Note: they will only show up after the first build is run

2020-12-16 13:16 UTC, moritzraho commented
LGTM,
Checks done:
- chrome: hitting the refresh button after a new deployment now refreshes content while it wasn't before 👌
- firefox: no noticeable changes (seems my FF is not caching js and css files)
- `aio app run`: checked that content hash is not applied here as it would break watch 👌 
- `aio app deploy`: made sure that previous files are deleted, as otherwise old static files would pile up

2020-12-17 06:45 UTC, sandeep-paliwal commented
@shazron I will create a separate PR for the CI changes you mentioned.

2020-12-21 06:48 UTC, shazron commented
> @shazron I will create a separate PR for the CI changes you mentioned.

thanks. That PR has to be merged in and those changes merged into this PR for this PR to pass CI.

2020-12-23 05:40 UTC, shazron requested changes

2020-12-23 05:40 UTC, shazron commented on test/src/build-web.test.js
> +    expect(global._bundler__arguments).toEqual(['fakeDir/index.html', { cache: false, contentHash: true, logLevel: 0, outDir: 'dist', publicUrl: './', watch: false }])
forward slash causing error in Windows tests. I'll fix

2020-12-23 05:49 UTC, shazron approved these changes

2020-12-23 05:51 UTC, merged

2021-01-09 02:06 UTC, alexkli commented
FWIW, I can confirm that this is fixed in `@adobe/aio-cli 5.0.1`.